---
name: compose
# yamllint disable-line rule:truthy
on: [push, pull_request]
jobs:
  webui-docker-compose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Verify that containers can be composed
        run: make test-containers-compose
