#!/bin/bash -e

# setup.
#
# It is expected to be run by a package trigger on initial install of
# the package and whenever there is a change to the packages involved
# in producing the generated assets, or alternatively, run once during
# package build with the generated assets included in the package.

generate() {
    npm run build
}

generate || exit $?
